export const GETBYID_PROFILE_REQUEST = "GETBYID_PROFILE_REQUEST";
export const GETBYID_PROFILE_SUCCESS = "GETBYID_PROFILE_SUCCESS";
export const GETBYID_PROFILE_FAIL = "GETBYID_PROFILE_FAIL";
export const GETBYID_PROFILE_RESET = "GETBYID_PROFILE_RESET";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCESS = "UPDATE_PROFILE_SUCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";

export const UPDATE_USER_TODO_REQUEST = "UPDATE_USER_TODO_REQUEST";
export const UPDATE_USER_TODO_SUCCESS = " UPDATE_USER_TODO_SUCCESS";
export const UPDATE_USER_TODO_FAIL = "UPDATE_USER_TODO_FAIL";
export const UPDATE_USER_TODO_RESET = "UPDATE_USER_TODO_RESET";

export const CREATE_USER_TODO_REQUEST = "CREATE_USER_TODO_REQUEST";
export const CREATE_USER_TODO_SUCCESS = " CREATE_USER_TODO_SUCCESS";
export const CREATE_USER_TODO_FAIL = "CREATE_USER_TODO_FAIL";
export const CREATE_USER_TODO_RESET = "CREATE_USER_TODO_RESET";

export const GET_USER_TODOBYID_REQUEST = "GET_USER_TODOBYID_REQUEST";
export const GET_USER_TODOBYID_SUCCESS = "GET_USER_TODOBYID_SUCCESS";
export const GET_USER_TODOBYID_FAIL = "GET_USER_TODOBYID_FAIL";
export const GET_USER_TODOBYID_RESET = "GET_USER_TODOBYID_RESET";

export const GETALL_USERS_TODO_REQUEST = "GETALL_USERS_TODO_REQUEST";
export const GETALL_USERS_TODO_SUCCESS = " GETALL_USERS_TODO_SUCCESS";
export const GETALL_USERS_TODO_FAIL = "GETALL_USERS_TODO_FAIL";
export const GETALL_USERS_TODO_RESET = "GETALL_USERS_TODO_RESET";

export const DELETE_USER_TODO_REQUEST = "DELETE_USER_TODO_REQUEST";
export const DELETE_USER_TODO_SUCCESS = " DELETE_USER_TODO_SUCCESS";
export const DELETE_USER_TODO_FAIL = "DELETE_USER_TODO_FAIL";
export const DELETE_USER_TODO_RESET = "DELETE_USER_TODO_RESET";
