export const GETBYID_PROFILE_REQUEST = "GETBYID_PROFILE_REQUEST";
export const GETBYID_PROFILE_SUCCESS = "GETBYID_PROFILE_SUCCESS";
export const GETBYID_PROFILE_FAIL = "GETBYID_PROFILE_FAIL";
export const GETBYID_PROFILE_RESET = "GETBYID_PROFILE_RESET";

export const UPDATE_USER_TODO_REQUEST = "UPDATE_USER_TODO_REQUEST";
export const UPDATE_USER_TODO_SUCCESS = " UPDATE_USER_TODO_SUCCESS";
export const UPDATE_USER_TODO_FAIL = "UPDATE_USER_TODO_FAIL";
export const UPDATE_USER_TODO_RESET = "UPDATE_USER_TODO_RESET";
