export const ADMIN_GETALL_TODO_REQUEST = "ADMIN_GETBYALL_TODO_REQUEST";
export const ADMIN_GETALL_TODO_SUCCESS = "ADMIN_GETBYALL_TODO_SUCCESS";
export const ADMIN_GETALL_TODO_FAIL = "ADMIN_GETBYALL_TODO_FAIL";
export const ADMIN_GETALL_TODO_RESET = "ADMIN_GETBYALL_TODO_RESET";

export const ADMIN_DELETE_TODO_REQUEST = "ADMIN_DELETE_TODO_REQUEST";
export const ADMIN_DELETE_TODO_SUCCESS = "ADMIN_DELETE_TODO_SUCCESS";
export const ADMIN_DELETE_TODO_FAIL = "ADMIN_DELETE_TODO_FAIL";
export const ADMIN_DELETE_TODO_RESET = "ADMIN_DELETE_TODO_RESET";

export const ADMIN_CREATE_TODO_REQUEST = "ADMIN_CREATE_TODO_REQUEST";
export const ADMIN_CREATE_TODO_SUCCESS = "ADMIN_CREATE_TODO_SUCCESS";
export const ADMIN_CREATE_TODO_FAIL = "ADMIN_CREATE_TODO_FAIL";
export const ADMIN_CREATE_TODO_RESET = "ADMIN_CREATE_TODO_RESET";

export const ADMIN_GETBYID_TODO_REQUEST = "ADMIN_GETBYID_USER_REQUEST";
export const ADMIN_GETBYID_TODO_SUCCESS = "ADMIN_GETBYID_USER_SUCCESS";
export const ADMIN_GETBYID_TODO_FAIL = "ADMIN_GETBYID_USER_FAIL";
export const ADMIN_GETBYID_TODO_RESET = "ADMIN_GETBYID_USER_RESET";
